spring:
  application:
    name: his-security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital2?serverTimezone=UTC
    username: root
    password: 060601hyz
  data:
    redis:
      host: localhost
      port: 6379
      password: 060601hyz
  cloud:
    nacos:
      discovery:
        server-addr: 111.230.250.144:8848
server:
  port: 8888


his-system-management:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule



mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml


hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 300m