spring:
  security:
    csrf:
      enabled: false
  main:
    web-application-type: reactive
  application:
    name: his-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital2?serverTimezone=UTC
    username: root
    password: 060601hyz
  data:
    redis:
      host: localhost
      port: 6379
      password: 060601hyz
  cloud:
    nacos:
      discovery:
        server-addr: 111.230.250.144:8848
    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - HEAD
#              - POST
#              - PUT
#              - DELETE
#              - TRACE
#              - OPTIONS
#              - PATCH
#            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: security
          uri: http://127.0.0.1:8888
          predicates:
            - Path=/security/**
        - id: systemanagement
          uri: http://127.0.0.1:9000
          predicates:
            - Path=/users/**,/roles/**,/permissions/**
        - id: bed
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/beds/**
        - id: patient
          uri: http://127.0.0.1:8085
          predicates:
            - Path=/patient/**


server:
  port: 9090


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

secure:
  openauthorization: true
  white:
    urls:
      - "/security/**"
      - "/user/**"

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 300m
