export interface Patient {
  patientId: number,
  name: string,
  age: number,
  gender: string,
  phone: string,
  admissionType: string,
  admissionTime: string,
  bookType: string,
  waitDay: number,
  isEmergency: number,
  isVIP: number,
  isAcute: number,
  roomNumberRequirement: number,
  roomTypeRequirement: string,
  roomGenderRequirement: string,
  patientStatus: string,
  admissionNumber: string,
  illness: string,
  doctor: string,
}

export interface Bed {
  bedId: number,
  campusName: string,
  officeName: string,
  wardName: string,
  roomName: string,
  bedNumber: number,
  bedType: string,
  roomType: string,
  roomNumber: number,
  roomGender: string,
  bedEquipment: string,
  status: string,
  patient: Patient | null
}
