export interface Patient {
  patientId: number,
  name: string,
  age: number,
  gender: string,
  phone: string,
  bookType: string | null,
  status: string,
  bedId: number | null,
  roomNumber: string | null,
  bedNumber: string | null,
  roomType: string | null,
  roomGender: string | null,
  bedCount: number | null,
  roomNumberRequirement: number | null,
  roomGenderRequirement: string | null,
  roomTypeRequirement: string | null,
  admissionType: string,
  admissionTime: string | null,
  createTime: string,
  dischargeTime: string | null;
  admissionNumber: string | null,
  waitDay: number | null,
  doctor: string,
  illness: string,
  isEmergency: number,
  isAcute: number,
  isVip: number
}